accounts/urls.py
from django.urls import path
from . import views
urlpatterns=[
    path('register',views.register,name="register"),
    path('login',views.login,name="login"),
    path('logout',views.logout,name="logout"),


]

cart/urls.py
from django.urls import path
from . import views
app_name='cart'
urlpatterns=[
    path('add/<int:product_id>/',views.add_cart,name="add_cart"),
    path('remove/<int:product_id>/', views.cart_remove, name="cart_remove"),
    path('full_remove/<int:product_id>/', views.full_remove, name="full_remove"),
    path('cart_detail',views.cart_detail,name="cart_detail"),
]

shopping_app/urls.py
from django.urls import path
from . import views
app_name='shopping_app'
urlpatterns = [

    path('', views.home,name='home'),
    path('<slug:c_slug>/', views.home, name='prod_cat'),
    path('<slug:c_slug>/<slug:product_slug>/',views.ProdCatDetail,name='ProdCatDetail'),
    path('search',views.SearchResult,name='search'),
    ]

shopping_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('shopping_app.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

cart/models.py
from django.db import models

# Create your models here.
from shopping_app.models import Product
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)

    class Meta:
        db_table='cart'
        ordering=['date_added']

    def __str__(self):
        return self.cart_id

class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)

    class Meta:
        db_table='CartItem'

    def sub_total(self):
        return self.product.price*self.quantity

    def __str__(self):
        return self.product

shopping_app/models.py
from django.db import models

# Create your models here.
from django.urls import reverse


class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse("shopping_app:prod_cat", args=[self.slug])



    def __str__(self):
        return '{}'.format(self.name)




class Product(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    desc = models.TextField(blank=True)
    image = models.ImageField(upload_to='product', blank=True)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    price = models.IntegerField()
    stock = models.IntegerField()
    available = models.BooleanField()

    def get_url(self):
        return reverse("shopping_app:ProdCatDetail", args=[self.category.slug, self.slug])

accounts/views.py
from django.contrib import messages
from django.shortcuts import render,redirect
from django.contrib.auth.models import User,auth
# Create your views here.

def login(request):
    if request.method == "POST":
        username = request.POST['username']
        password1 = request.POST['password1']
        user = auth.authenticate(username=username, password=password1)
        if user is not None:
            auth.login(request,user)
            return redirect('/')
        else:
            messages.info(request,'invalid details')
            return redirect('login')
    else:
        return render(request,"login.html")


def register(request):
    if request.method=="POST":
        first_name=request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        email = request.POST['email']
        if password1==password2:
            if User.objects.filter(username=username).exists():
                messages.info(request,"username taken")
                return redirect('register')
            elif User.objects.filter(email=email).exists():
                messages.info(request,"email taken")
                return redirect('register')
            else:
                user=User.objects.create_user(username=username,password=password1,email=email,first_name=first_name,last_name=last_name)
                user.save()
                print("user created")
        else:
            print("password not matched")
            return redirect('register')
        return redirect('/')
    else:


         return render(request,'registration.html')


def logout(request):
    auth.logout(request)
    return redirect('/')

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shopping_app.models import Product
from . models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist

def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart

def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(cart_id=_cart_id(request))
        cart.save()


    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(product=product,quantity=1, cart=cart )

    return redirect('cart:cart_detail')

def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total += cart_item.product.price * cart_item.quantity
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,"cart.html",dict(cart_items=cart_items,total=total,counter=counter))

def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity>1:
        cart_item.quantity-=1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')
#
def full_remove(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

shopping_app/views.py
from django.core.paginator import Paginator, EmptyPage, InvalidPage
from django.shortcuts import render, get_object_or_404
from . models import *
from django.db.models import Q
# Create your views here.
def home(request,c_slug=None):
    c_page = None
    products = None
    if c_slug != None:
        c_page = get_object_or_404(Category, slug=c_slug)
        products = Product.objects.filter(category=c_page, available=True)
    else:
        products = Product.objects.all().filter(available=True)
    cat=Category.objects.all()
    # paginator = Paginator(products, 6)
    # try:
    #     page=int(request.GET.get('page',1))
    # except:
    #      page=1
    # try:
    #      pro=paginator.page(page)
    # except (EmptyPage,InvalidPage):
    #      pro=paginator.page(paginator.num_pages)
    return render(request,'index.html',{'pr':products,'ct':cat})

def ProdCatDetail(request,c_slug,product_slug):
    try:
        prod=get_object_or_404(Product,category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,'item.html',{'pr':prod})

def SearchResult(request):
    prod=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        prod=Product.objects.all().filter(Q(name__contains=query) | Q(desc__contains=query))
    return render(request,"search.html",{'qr':query,'pr':prod})

templates/base.html
{% load static %}
<!--
Template Name: Yammoe
Author: <a href="https://www.os-templates.com/">OS Templates</a>
Author URI: https://www.os-templates.com/
Copyright: OS-Templates.com
Licence: Free to use under our free template licence terms
Licence URI: https://www.os-templates.com/template-terms
-->
<html lang="">
<!-- To declare your language - read more here: https://www.w3.org/International/questions/qa-html-language-declarations -->
<head>
<title>Yammoe</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<link href="{% static 'all/layout/styles/layout.css' %}" rel="stylesheet" type="text/css" media="all">
</head>
<body id="top">
<!-- ################################################################################################ -->
  <!-- ################################################################################################ -->
  <div class="wrapper row1">
    <header id="header" class="hoc clear">
      <div id="logo" class="fl_left">
        <!-- ################################################################################################ -->
        <h1><a href="/">Yammoe</a></h1>
        <!-- ################################################################################################ -->
      </div>
      <nav id="mainav" class="fl_right">
        <!-- ################################################################################################ -->
        <ul class="clear">
          <li class="active"><a href="/">Home</a></li>
          <li><a href="{% url 'cart:cart_detail' %}">Cart</a></li>
          {% if user.is_authenticated %}
          <li>Hai {{user.username}}</li>
          <li><a href="accounts/logout">Logout</a></li>
          {% else %}
          <li><a href="accounts/login">Login</a></li>
          <li><a href="accounts/register/">Register</a></li>
          {% endif %}
        </ul>
        <!-- ################################################################################################ -->
      </nav>
    </header>
  </div>
{% block content %}
{% endblock %}
</body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Cart | E-Shopper</title>
    <link href="{% static 'cr/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'cr/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'cr/css/prettyPhoto.css' %}" rel="stylesheet">
    <link href="{% static 'cr/css/price-range.css' %}" rel="stylesheet">
    <link href="{% static 'cr/css/animate.css' %}" rel="stylesheet">
	<link href="{% static 'cr/css/main.css' %}" rel="stylesheet">
	<link href="{% static 'cr/css/responsive.css' %}" rel="stylesheet">
    <!--[if lt IE 9]>
    <script src="{% static 'js/html5shiv.js' %}"></script>
    <script src="{% static 'js/respond.min.js' %}"></script>
    <![endif]-->
    <link rel="shortcut icon" href="{% static 'cr/images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static 'cr/images/ico/apple-touch-icon-144-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static 'cr/images/ico/apple-touch-icon-114-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static 'cr/images/ico/apple-touch-icon-72-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" href="{% static 'cr/images/ico/apple-touch-icon-57-precomposed.png' %}">
	<style>
		body {
  background: #76b852; /* fallback for old browsers */
  background: -webkit-linear-gradient(right, #76b852, #8DC26F);
  background: -moz-linear-gradient(right, #76b852, #8DC26F);
  background: -o-linear-gradient(right, #76b852, #8DC26F);
  background: linear-gradient(to left, #76b852, #8DC26F);
  font-family: "Roboto", sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}


	</style>
</head><!--/head-->

<body>


	<section id="cart_items">
		<div class="container">
								<table class="table table-condensed">

					<thead>
						<tr class="cart_menu">
							<td>Item</td>
							<td></td>
							<td>Price</td>
							<td>Quantity</td>
							<td>Total</td>
							<td></td>
						</tr>
					</thead>
					{% for i in cart_items %}
					<tbody>
					    <tr>
							<td>
								<a href="{{i.product.get_url}}"><img src="{{i.product.image.url}}" alt="{{i.product.name}}" style="height: 70; width: 70;"></a>
							</td>
							<td>
								<h4><a href="">{{i.product.name}}</a></h4>
							</td>
							<td>
								<p>${{i.product.price}} </p>
							</td>
							<td>
								<div class="cart_quantity_button">
									<a class="cart_quantity_up" href="{% url 'cart:add_cart' i.product.id %}"> + </a>
									<input class="cart_quantity_input" type="text" name="quantity" value="{{i.quantity}}" autocomplete="off" size="2">
									<a class="cart_quantity_down" href="{% url 'cart:cart_remove' i.product.id %}"> - </a>
								</div>
							</td>
							<td>
								<p class="cart_total_price">${{i.sub_total}}</p>
							</td>
							<td>
								<a class="cart_quantity_delete" href="{% url 'cart:full_remove' i.product.id %}"><i class="fa fa-times"></i></a>
							</td>
						</tr>
					</tbody>
					{% endfor %}
				</table>
				<p>Total: <span class="price" style="color:black; background-color:#4CAF50; font-family:'comic sams ms';"><b>Total:${{total}}</b></span></p>
			</div>
		</div>
	</section> <!--/#cart_items-->




    <script src="{% static 'cr/js/jquery.js' %}"></script>
	<script src="{% static 'cr/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'cr/js/jquery.scrollUp.min.js' %}"></script>
    <script src="{% static 'cr/js/jquery.prettyPhoto.js' %}"></script>
    <script src="{% static 'cr/js/main.js' %}"></script>
</body>
</html>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!--
Template Name: Yammoe
Author: <a href="https://www.os-templates.com/">OS Templates</a>
Author URI: https://www.os-templates.com/
Copyright: OS-Templates.com
Licence: Free to use under our free template licence terms
Licence URI: https://www.os-templates.com/template-terms
-->
<html lang="">
<!-- To declare your language - read more here: https://www.w3.org/International/questions/qa-html-language-declarations -->
<head>
<title>Yammoe</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<link href="{% static 'all/layout/styles/layout.css' %}" rel="stylesheet" type="text/css" media="all">
  <style>
  .dropbtn {
  background-color: #4CAF50;
  color: white;
  padding: 16px;
  font-size: 16px;
  border: none;
  cursor: pointer;
}

.dropdown {
  position: relative;
  display: inline-block;
  padding-left: 10px;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f9f9f9;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
}

.dropdown-content a:hover {background-color: #f1f1f1}

.dropdown:hover .dropdown-content {
  display: block;
}

.dropdown:hover .dropbtn {
  background-color: #3e8e41;
}
.abcd{
  height: 100%;
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
  }

</style>
</head>
<body id="top">
<!-- ################################################################################################ -->
  <!-- ################################################################################################ -->

<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<!-- Top Background Image Wrapper -->
<div class="abcd" style="background-image:url('{% static 'all/images/demo/backgrounds/01.png' %}');">
  <!-- ################################################################################################ -->
<div class="wrapper row0">
    <div id="topbar" class="hoc clear">
  <div class="fl_right">
        <!-- ################################################################################################ -->
        <ul class="nospace">

          <li id="searchform">
            <div>
              <form action="{% url 'shopping_app:search' %}" method="get">
                <fieldset>
                  <legend>Quick Search:</legend>
                  <input type="text" placeholder="Enter item name to search" name="q">
                  <button type="submit"><i class="fas fa-search"></i></button>
                </fieldset>
              </form>
            </div>
          </li>
        </ul>
    </div>
  </div>

   <div class="dropdown">
  <button class="dropbtn">FILTER</button>
  <div class="dropdown-content">
  <a href="/">ALL</a>
    {% for i in ct %}
  <a href={{i.get_url}}>{{i.name}}</a>
   {% endfor %}
  </div>
</div>
</div>



  <!-- ################################################################################################ -->
  <!-- ################################################################################################ -->
  <!-- ################################################################################################ -->
  <div id="pageintro" class="hoc clear">
    <!-- ################################################################################################ -->
    <article>
      <p>Habitant morbi tristique</p>
      <h3 class="heading">Senectus et netus</h3>
       <footer>

       </footer>
    </article>
    <!-- ################################################################################################ -->
  </div>
  <!-- ################################################################################################ -->
</div>
<!-- End Top Background Image Wrapper -->
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->

<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->

<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
>
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->

<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<div class="wrapper row2">
  <section class="hoc container clear">
    <!-- ################################################################################################ -->

    <ul id="latest" class="nospace group sd-third">
      {% for i in pr %}
      <li class="one_third">
        <article>
          <figure><a class="imgover" href="{{i.get_url}}"><img src="{{i.image.url}}" alt="" style="height: 200; width: 200"></a>
            <figcaption>
              <h6 class="heading">{{i.name}}</h6>
              <p>{{i.desc|truncatewords:17}}</p>
            </figcaption>
          </figure>
        </article>
      </li>
      {% endfor %}
<!--      <li class="one_third">-->
<!--        <article>-->
<!--          <figure><a class="imgover" href="#"><img src="{% static 'all/images/demo/348x261.png' %}" alt=""></a>-->
<!--            <figcaption>-->
<!--              <p>Sed varius fringilla dolor metus iaculis odio ac scelerisque nibh velit sagittis tellus nulla</p>-->
<!--              <footer><a class="btn" href="#">Read More</a></footer>-->
<!--            </figcaption>-->
<!--          </figure>-->
<!--        </article>-->
<!--      </li>-->
<!--      <li class="one_third">-->
<!--        <article>-->
<!--          <figure><a class="imgover" href="#"><img src="{% static 'all/images/demo/348x261.png' %}" alt=""></a>-->
<!--            <figcaption>-->
<!--              <p>Nulla facilisi integer adipiscing turpis cras quis neque at lectus tincidunt consectetuer</p>-->
<!--              <footer><a class="btn" href="#">Read More</a></footer>-->
<!--            </figcaption>-->
<!--          </figure>-->
<!--        </article>-->
<!--      </li>-->
    </ul>
    <!-- ################################################################################################ -->
  </section>
</div>
<!-- ################################################################################################ -->
<!-- JAVASCRIPTS -->
<script src="{% static 'all/layout/scripts/jquery.min.js' %}"></script>
<script src="{% static 'all/layout/scripts/jquery.backtotop.js' %}"></script>
<script src="{% static 'all/layout/scripts/jquery.mobilemenu.js' %}"></script>
</body>
</html>
{% endblock %}

templates/item.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400" rel="stylesheet" />
    <link href="{% static 'pr/fontawesome/css/all.min.css' %}" rel="stylesheet" />
    <link href="{% static 'pr/css/templatemo-comparto.css' %}" rel="stylesheet" />
    <title>Comparto HTML CSS Template</title>
<!--

Comparto TemplateMo

https://templatemo.com/tm-544-comparto

-->
</head>

<body>
    <!-- Back to top button -->
  <br><br>
        <section class="tm-mb-1" id="about">
            <div class="tm-row tm-about-row">
                <div class="tm-section-1-l">
                    <img src="{{pr.image.url}}" alt="About image" class="tm-img-responsive" style="height: 400; width: 400;">
                </div>
                <article class="tm-section-1-r tm-bg-color-8">
                    <h2 class="tm-mb-2 tm-title-color">{{pr.name}}</h2>
                    <p>Price: {{pr.price}}Rs <br> {{pr.desc}}</p>
                    <p>Stock: {{pr.stock}}</p>
                    {% if pr.stock <= 0 %}
                        <h1 style="color: red">Sorry, No stock left</h1>
                    {% else %}
                        <a href="{% url 'cart:add_cart' pr.id %}" class="tm-btn tm-btn-1 tm-link-to-services">Add To Cart</a>
                    {% endif %}
                </article>
            </div>
        </section>
      
</body>
</html>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Login | E-Shopper</title>
    <link href="{% static 'cr/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'cr/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'cr/css/prettyPhoto.css' %}" rel="stylesheet">
    <link href="{% static 'cr/css/price-range.css' %}" rel="stylesheet">
    <link href="{% static 'cr/css/animate.css' %}" rel="stylesheet">
	<link href="{% static 'cr/css/main.css' %}" rel="stylesheet">
	<link href="{% static 'cr/css/responsive.css' %}" rel="stylesheet">
    <!--[if lt IE 9]>
    <script src="{% static 'cr/js/html5shiv.js' %}"></script>
    <script src="{% static 'cr/js/respond.min.js' %}"></script>
    <![endif]-->
    <link rel="shortcut icon" href="images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static 'cr/images/ico/apple-touch-icon-144-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static 'cr/images/ico/apple-touch-icon-114-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static 'cr/images/ico/apple-touch-icon-72-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" href="{% static 'cr/images/ico/apple-touch-icon-57-precomposed.png' %}">
	<style>
		.login-page {
  width: 360px;
  padding: 8% 0 0;
  margin: auto;
}
.form {
  position: relative;
  z-index: 1;
  background: #FFFFFF;
  max-width: 360px;
  margin: 0 auto 100px;
  padding: 45px;
  text-align: center;
  box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
}
.form input {
  font-family: "Roboto", sans-serif;
  outline: 0;
  background: #f2f2f2;
  width: 100%;
  border: 0;
  margin: 0 0 15px;
  padding: 15px;
  box-sizing: border-box;
  font-size: 14px;
}
.form button {
  font-family: "Roboto", sans-serif;
  text-transform: uppercase;
  outline: 0;
  background: #4CAF50;
  width: 100%;
  border: 0;
  padding: 15px;
  color: #FFFFFF;
  font-size: 14px;
  -webkit-transition: all 0.3 ease;
  transition: all 0.3 ease;
  cursor: pointer;
}
.form button:hover,.form button:active,.form button:focus {
  background: #43A047;
}
.form .message {
  margin: 15px 0 0;
  color: #b3b3b3;
  font-size: 12px;
}
.form .message a {
  color: #4CAF50;
  text-decoration: none;
}
.form .register-form {
  display: none;
}
.container {
  position: relative;
  z-index: 1;
  max-width: 300px;
  margin: 0 auto;
}
.container:before, .container:after {
  content: "";
  display: block;
  clear: both;
}
.container .info {
  margin: 50px auto;
  text-align: center;
}
.container .info h1 {
  margin: 0 0 15px;
  padding: 0;
  font-size: 36px;
  font-weight: 300;
  color: #1a1a1a;
}
.container .info span {
  color: #4d4d4d;
  font-size: 12px;
}
.container .info span a {
  color: #000000;
  text-decoration: none;
}
.container .info span .fa {
  color: #EF3B3A;
}
body {
  background: #76b852; /* fallback for old browsers */
  background: -webkit-linear-gradient(right, #76b852, #8DC26F);
  background: -moz-linear-gradient(right, #76b852, #8DC26F);
  background: -o-linear-gradient(right, #76b852, #8DC26F);
  background: linear-gradient(to left, #76b852, #8DC26F);
  font-family: "Roboto", sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
h1 {
  font-size: 3em;
  text-align: center;
  color: #000000;
  font-weight: 100;
  text-transform: capitalize;
  letter-spacing: 4px;
  font-family: 'Roboto', sans-serif;
}





	</style>
</head><!--/head-->

<body>
<form action="login" method="post">
<div class="login-page">
	<h1>Login</h1>
        {% csrf_token %}
        <div class="form">
              <input type="text" name="username"  placeholder="Username"/>
              <input type="password" name="password1" placeholder="password"/>
              <button>login</button>
          </div>
</div>
</form>





    <script src="{% static 'cr/js/jquery.js"></script>
	<script src="{% static 'cr/js/price-range.js"></script>
    <script src="{% static 'cr/js/jquery.scrollUp.min.js"></script>
	<script src="{% static 'cr/js/bootstrap.min.js"></script>
    <script src="{% static 'cr/js/jquery.prettyPhoto.js"></script>
    <script src="{% static 'cr/js/main.js"></script>
</body>
</html>
{% endblock %}